### ISSUE TITLE
implementacia skratiek

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#11]
https://stackoverflow.com/questions/23052257/multiple-key-press-on-javafx-scene

**Comment by muriga** [comment]
Pripravím to, akurát mám otázku - hodil si tu otázku k tomu ako riešiť multiple key press. To ale zatiaľ nie je naša situácia, nie? Pozerám sa na súbor PopisBackendu a z neho mi vychádza, že zatiaľ treba poriešiť iba rozlíšenie malých a veľkých písmen (teda Shift+písmeno)

**Comment by muriga** [comment]
Toto si sem odložím:
https://stackoverflow.com/questions/37494891/puzzling-keyevent-handling-for-lowercase-letters
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/input/KeyCombination.html#valueOf-java.lang.String-

**Comment by nofiv** [comment]
Commit https://github.com/TIS2020-FMFI/dalekohlad/commit/616df63053982d84f2c7f822ee608cbe6433a05f implementuje spracovanie vsetkych skratiek priamo v handleri eventov, ale nie je jasne ako sa odtial budu volat prislusne funkcie jednotlivych modulov. V commite https://github.com/TIS2020-FMFI/dalekohlad/commit/d60a151e6835539fb43a096f97c7c09e7f0ee084 su upravy, ktore daju kazdemu modulu moznost implementovat si vlastne skratky a priradit k nim priamo prislusne funkcie

**Comment by nofiv** [comment]
Priklonili sme sa k druhej alternative a kazdy implementuje skratky podla vlastneho uvazenia v bloku s ktorym bude pracovat po mergnuti #28 , [priklad](https://github.com/TIS2020-FMFI/dalekohlad/blob/d60a151e6835539fb43a096f97c7c09e7f0ee084/src/main/java/fmfi/dalekohlad/Modules/Dome.java#L29)
