### ISSUE TITLE
implementacia grafiky aktuálny smer ďalekohľadu

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#13]
poziadavky 3.5.6 a 3.6.6

**Comment by petrilak3** [comment]
Riešenie zobrazenia grafiky:
- systém zobrazí smer ďalekohľadu ako "kompas", kde ručička bude ukazovať buď na sever,východ,juh, alebo medzi jednotlivými svetovými stranami.

Nech C je kružnica (predstavujúca okraj kompasu) so stredom S a polomerom r. 
Nech R je ručička (line), ktorá je zodpovedná za ukážku smeru ďalekohľadu vzhľadom na svetové strany.

V GUI bude jasne definovaná kružnica, stred kružnice (centerX & centerY) a zároveň aj polomer (r). Takže tieto časti sú dopredu známe.
Podobne vieme, že ručička bude mať začiatok v strede kružnice (centerX,centerY).

Problém: Kde bude mať ručička presný koniec a ako zobrazíme polohu podľa stupňov (uloh)?

Riešenie:
- nech "u" sú stupne, ktoré chceme zobraziť (napr. u=90°)
- rozdelíme si kružnicu na 360 častí (360°), vynásobíme dvomi a zároveň vynásobíme naším uhlom, ktorý chceme zobraziť. Takto nám vznikne uhol alpha = u * 2 * Math.PI/360
- potrebujeme zistiť dĺžku ručičky - length. Dĺžku bude rovná polomeru kružnice. Z toho vyplýva, že length = r

- výsledná ručička bude mať koniec v x-ovom smere => centerX + length*Math.sin(alpha)
- výsledná ručička bude mať koniec v y-lonovom smere = > centerY - length*Math.cos(alpha)

Teraz sú známe všetky potrebné hodnoty na vytvorenie grafického zobrazenia smeru ďalekohľadu

ukážka:
https://www.figma.com/file/i4bvmytIU5erKeipcmMXFh/Untitled?node-id=0%3A1

**Comment by petrilak3** [comment]
Logika funkčná. Samotná implementácia sa rieši v issue : #40
