### ISSUE TITLE
vykreslenie nahladu poslednej vytvorenej snimky

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#17]

**Comment by muriga** [comment]
https://github.com/nom-tam-fits/nom-tam-fits
https://heasarc.gsfc.nasa.gov/docs/heasarc/fits/

**Comment by petrilak3** [comment]
FITS library : astroImageJ

FITS snímka a AMOS snímka od zadávateľov: [Click here...](https://liveuniba-my.sharepoint.com/personal/silha1_uniba_sk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsilha1_uniba_sk%2FDocuments%2FAGO70_GUI&ct=1605264982203&or=OWA-NT&cid=54722597-6915-9ec9-1931-eb6712aee62e&originalPath=aHR0cHM6Ly9saXZldW5pYmEtbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvc2lsaGExX3VuaWJhX3NrL0VvdFFuU0FKanZaS21KRnlON05xd1ZJQl8yTjZNcDA2SkgzRF9xUG5nLXZjaXc_cnRpbWU9cnBPVnc4S0gyRWc)

**Comment by muriga** [comment]
Access denied..

**Comment by petrilak3** [comment]
https://drive.google.com/file/d/1ceaDm-d9ZJBgOOdcmmVF8Zd9YX-vJZz6/view?usp=sharing

Reupload na drive.
