### ISSUE TITLE
návrh používateľského rozhrania

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#21]
návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom

**Comment by petrilak3** [comment]
Preskúmavanie programu na vytvorenie grafiky návrhu : [www.moqups.com](url)

**Comment by petrilak3** [comment]
Prvý cvičný návrh UI pre projekt ďalekohľad : https://app.moqups.com/pZfH0whacO/view/page/ad64222d5

**Comment by nofiv** [comment]
> Prvý cvičný návrh UI pre projekt ďalekohľad : https://app.moqups.com/pZfH0whacO/view/page/ad64222d5

"Access Denied     You need permission to view this project."

**Comment by petrilak3** [comment]
Dokončená prvá časť GUI (main), okrem nastaviteľných parametrov pre Target a Filterwheel + vyskakovacie okná: Klávesové skratky & Last frame. Návrh bude dnes do polnoci odoslaný zadávateľom ako beta verzia a budem očakávať feedback. Zároveň napíšem informáciu o preplnenosti (viď. issues)

**Comment by pavelpetrovic** [comment]
zatiaľ paráda

**Comment by petrilak3** [comment]
UPDATE: dnes 29.10.2020 o 12:00 prišla odpoveď na návrh : _ďakujeme Vám za dokumenty, v priebehu budúceho týždňa Vám ich pošleme späť s prípadnými poznámkami — aj pre wireframe z predchádzajúceho mailu._

**Comment by petrilak3** [comment]
UPDATE: 

1.  do návrhu boli pridané 2 rôzne grafické návrhy na zobrazenie daný grafík (viď. KP)
2.  do návrhu boli pridané ďalšie stránky, kt. sú : shortcuts, notification type 1, notification type 2
3.  z dôvodu obmedzených možností bude stránke s klávesovými skratkami naplnená samostatne a vložená ako obrázok do hlavného návrhu

Dané body s výnimkou bodu 3 boli pridané do hlavného návrhu ešte pred prvým prezretím návrhu zadávateľmi. Ostatné časti budú pridané až po odpovedi zadávateľov na konkrétny návrh spolu so zapracovaním pripomienok zadávateľov.

Čo sa týka teamu, návrh bol schválený na stretnutí z dňa 3.11.2020.

**Comment by pavelpetrovic** [comment]
dostali ste, prosim, odozvu od zadavatelov?

**Comment by petrilak3** [comment]
@pavelpetrovic Nie. Zatiaľ bez odozvy ako aj na návrh, tak aj na katalóg požiadaviek.

**Comment by muriga** [comment]
Ešte mi napadlo, že možno bude treba ďalšiu notifikáciu: V prípade, že nebudú pripojený na server, prípadne ak iba napr. dome bude mať divný status a užívateľ sa bude snažiť robiť niečo napr. s dome.

**Comment by muriga** [comment]
A inak, rozmýšľam znova nad tými notogikáciami.. nemalo by to byť naopak?
Case 1: Zadám niečo nie pochybné, čo by ale mohlo byť teoreticky zamýšľané. To je vhodné vyhodiť nejaký warning. Ibaže tam sa môže stať a) naozaj som to chcel zadať, b) pomýlil som sa. Ak je to a) chcem len odkliknúť warning že beriem na vedomie, pošli to. Pri b) to nechcem poslať a vrátiť sa k zadávaniu. 
Ak je to skutočne invalid input, či chcem či nechcem, musím sa vrátiť k zadávaniu toho čo bolo invalid.

**Comment by petrilak3** [comment]
@nofiv @muriga @13andrej 

Finalizoval som návrh GUI zapracovaním všetkých bodov od zadávateľa. Prosím napíšte, či ste s tým okej. 
* čo sa týka tých grafík. Nakreslil som 2x grafiku namiesto jednej grafiky obsahujucej 2 udaje. Bolo miesto a je to aj lepšie a zrozumiteľnejšie podľa môjho názoru. Ak nebudete súhlasiť, necháme 3 zobrazenia, kde budú zobrazené smerovania v 1 grafike.

A poprosím feedback najneskôr do piatku. Na stretku v piatok to budem prezentovať ako druhý finálny návrh.

**Comment by nofiv** [comment]
Za mňa môže byť

**Comment by muriga** [comment]
Čo sa týka rozdelenie na viac grafík, za mňa tiež môže byť, aj čo sa týka prevedenia. Mám akurát jednu poznámku na zváženie: možno by bolo fajn prostredné dve grafiky nejak rozlíšiť (napr. text pod nimi) aby bolo jasné, ktorá sa týka ďalekohľadu a ktorá kupoly, keďže sú rovnaké a ešte aj pri sebe. No a určite by to rozlíšenie bolo fajn, keby tá naľavo patrila k ďalekohľadu, keďže jeho sa týka aj prvá grafika.

**Comment by petrilak3** [comment]
**Update:** 
Návrhu používateľského rozhrania je dokončený. Momentálne sa čaká na definitívne (oficiálne) schválenie návrhu používateľského rozhrania od zadávateľov.

**Comment by petrilak3** [comment]
**Update:**

Návrh bol oficiálne schválený.
