### ISSUE TITLE
Zrozumiteľný a jednoznačný návrh implementácie

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#22]
Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by muriga** [comment]
[Link](https://liveuniba-my.sharepoint.com/:w:/r/personal/uriga3_uniba_sk/Documents/N%C3%A1vrh%20rie%C5%A1enia.docx?d=w13970027301e49b9a787cd4889daf45d&csf=1&web=1&e=aQaJVv) na dokument Návrh riešenia

**Comment by muriga** [comment]
Sekvenčný diagram (je ešte v procese tvorby): 
https://drive.google.com/file/d/1eautvXtiS99Z5uBpabIexhkytl-B8Bid/view?usp=sharing

**Comment by 13andrej** [comment]
prvotný návrh stavového diagramu:
https://drive.google.com/file/d/1UA8b8iPb36W-PMxR3xlB0iDKg9hdcX9o/view?usp=sharing

**Comment by muriga** [comment]
Doplnený sekvenčný diagram možno nájsť na horeuvedeom linku alebo v dokumente návrhu.

**Comment by 13andrej** [comment]
Component diagram: predbežný návrh: https://drive.google.com/file/d/1xTeoYx7DXBRztzs9EEGqOQxvQWa48Ed-/view?usp=sharing

súbor: https://drive.google.com/file/d/1mVgSkeJG2_r8NaBRpUSPAPzpj63Xz7Vf/view?usp=sharing

stavový aj komponent diagram sú robené pomocou : https://app.diagrams.net

**Comment by 13andrej** [comment]
![Package dalekohlad4](https://user-images.githubusercontent.com/61241858/99712488-68219800-2aa3-11eb-9f3f-8253b050d44b.png)

ešte neúplný class diagram, pribudnú ešte nejaké triedy

**Comment by petrilak3** [comment]
@13andrej keďže je už implementovaný aj posledný modul, ktorý bol potrebný na úplný class diagram, tak by bolo asi fajn ho vygenerovať a vložiť do návrhu. Keďže už to máš naštudované a otestované cez IntelliJ, tak píšem tebe :)

**Comment by 13andrej** [comment]
![Package dalekohlad](https://user-images.githubusercontent.com/61241858/101644290-4cbc0400-3a35-11eb-8d28-c074da05dbf1.png)

**Comment by nofiv** [comment]
vybavene
