### ISSUE TITLE
JSON file and emulator

### ISSUE THREAD

**Issue by petrilak3** [TIS2020-FMFI/dalekohlad#26]
Momentálne stále nebol doručený okomentovaný JSON a Emulátor, kt. sú dôležité pri tvorbe apk.

**Comment by nofiv** [comment]
Dnes nam prisiel emulator vo forme vytrhnuteho neskompilovatelneho kodu (sucast archivu s sha1:c5d40b696b060294db3841dc84a2dd642c2b2c18). JSON nebol poslany pretoze podla zadavatela budeme vsetko schopni vycitat z emulatora. Ma byt v stave kde si podla zadavatela budeme "musieť nahradiť premenné zo systémov ďalekohľadu nejakými dummy premennými". Definicie typov tychto premennych nikde nevidim a tym padom by sme museli tipnut vsetky tieto typy(viac ako 100), pri nasadeni do prevadzky by si zadavatel musel opat prisposobovat kod nasim tipom. Taktiez chyba definicia viacerych funkcii ako sg() a Angle(), ktorych vystup sa da hadat este tazsie. Ak mi nieco uslo a mylim sa, opravte ma prosim. Ak nie, je asi potrebne opat sa ozvat zadavatelovi.

**Comment by nofiv** [comment]
Dodany bol nakoniec iba emulator z ktoreho sa da vycitat format JSON suboru(#16)
