### ISSUE TITLE
dohodnut termin pravidelnych tyzdennych stretnuti s cviciam

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#3]
Prvy navrh utorok 08:30

**Comment by pavelpetrovic** [comment]
v utorok o 8:30 mam naplanovane stretnutia so skupinou MMLC, skuste navrhnut dalsi termin, prosim.

**Comment by nofiv** [comment]
bol dohodnuty stvrtok 20:00
