### ISSUE TITLE
startovanie skriptu na spracovanie planu

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2020-FMFI/dalekohlad#32]
len keby sa nahodou hodilo, pripajam moje jednoduche ukazky ako odstartovat z pythonu alebo z javy externy proces s presmerovanym vstupom a vystupom - cize program, ktory ho odstartoval moze pisat do jeho standardneho vstupu a citat z jeho standardneho vystupu. programy by sa mali dat pustit na win10
[s.zip](https://github.com/TIS2020-FMFI/dalekohlad/files/5535936/s.zip)

p.

**Comment by petrilak3** [comment]
Ďakujeme pekne.

**Comment by nofiv** [comment]
hotovo
