### ISSUE TITLE
implementacia modulu Axis

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#39]

**Comment by muriga** [comment]
Napadla mi taká vec, možno to máš premyslené lepšie, ak hej, pokojne ignoruj.
No ale ak nie možno budú moje úvahy užitočné: v katalógu požiadaviek máme pre pohyb motorov v RA smere (3.5.3) požiadavku, že po stlačení ľavej šipky sa zadá hodnota 1 - 250 000 a pôjde to jedným smerom, ak sa stlačí šipka vpravo, pôjde to opačným smerom. Vo fáze návrhu GUI ale zmenili rozsah na -250 000 až 250 000 a iba jeden input. Čiže bude treba vyriešiť ako handlovať tieto šipky. Môj návrh je dať pri stlačení ľavej šipky focus na textfield a už predpísané "-". 

To len také úvahy popri hľadaní scenárov :D

**Comment by petrilak3** [comment]
modul Axis bol implementovaný
