### ISSUE TITLE
implementacia modulu Graphics

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#40]
zavisle od #13 a #14

**Comment by petrilak3** [comment]
UPDATE:
vytvoreny modul Graphics a implementovaná prvá grafika - sklon nad horizontom spolu s validaciou -> pod 25° (Elevation) červený rámček + stredový bod (inak zelený)

**Comment by petrilak3** [comment]
Implementované druhé grafické zobrazenie - smerovanie kupoly a dalekohladu

**Comment by petrilak3** [comment]
Implemented
