### ISSUE TITLE
vytvorenie testovacích scenárov

### ISSUE THREAD

**Issue by muriga** [TIS2020-FMFI/dalekohlad#43]

**Comment by petrilak3** [comment]
Pozrel som si testovacie scenáre a myslím, že sú fajn a sedia. Dopísal som zopár bodov (pripomienok)ako revíziu, takže si to môžeš pozrieť a buď potvrdiť / zamietnuť.

**Comment by muriga** [comment]
Okej, vďaka. Prijal som navrhované zmeny dokumentu a teraz by podľa mňa už mal byť vo finálnej verzii.
