### ISSUE TITLE
conected status error

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#64]
pri 2. disconnecte mi ostal status stale "connected", ma niekto podobny problem?

**Comment by muriga** [comment]
Ako myslíš po 2. disconnecte?
Ja mám skôr ten problém, že keď vypnem emulátor, a potom znovu zapnem, už sa mi nepripojí, ale iba vypisuje:
ERROR fmfi.dalekohlad.Communication.Communication - Failed to read data, repeating...
Resp. aj keď najprv zapnem najprv GUI a potom neskôr emulátor, nevie sa mi to pripojiť.

**Comment by muriga** [comment]
Je to zakomponované v #70 môžeš to prosím otestovať?

**Comment by nofiv** [comment]
v #70 funguje ako ma
