### ISSUE TITLE
po vypnuti a opatovnom zapnuti emulatoru sa aplikacia nedokaze v niektorych pripadoch spatne pripojit

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#67]
Ako myslíš po 2. disconnecte?
Ja mám skôr ten problém, že keď vypnem emulátor, a potom znovu zapnem, už sa mi nepripojí, ale iba vypisuje:
ERROR fmfi.dalekohlad.Communication.Communication - Failed to read data, repeating...

_Originally posted by @muriga in https://github.com/TIS2020-FMFI/dalekohlad/issues/64#issuecomment-742270095_

**Comment by nofiv** [comment]
nedokazem to zreprodukovat, ma niekto podobny problem?

**Comment by nofiv** [comment]
@muriga  daj prosim na tento riadok https://github.com/TIS2020-FMFI/dalekohlad/blob/master/src/main/java/fmfi/dalekohlad/Communication/Communication.java#L82 este ", e" a daj vediet prosim aka presne tam je chyba

**Comment by muriga** [comment]
Takže, ak emulátor vypnem a potom znovu zapnem, exception message je: fmfi.dalekohlad.Communication.Communication - Connection reset

**Comment by nofiv** [comment]
@muriga skus toto prosim https://github.com/TIS2020-FMFI/dalekohlad/tree/nofiv-patch-1

**Comment by muriga** [comment]
Môžeš prosím [tú vetvu](https://github.com/TIS2020-FMFI/dalekohlad/tree/nofiv-patch-1) potiahnúť do mastra?

Včera mi síce nejakým zázrakom fungovala aj staršia verzia, no dnes už nie, kým toto funguje, zdá sa, spoľahlivo.
