### ISSUE TITLE
katalog poziadaviek

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#7]
vytvorit z poznamok zo stretnutia (https://liveuniba-my.sharepoint.com/:w:/g/personal/petrilak3_uniba_sk/EbeXTeLmpEBEsMMkQiILyO4BEchyYpyZggYy_nIsxatPxA?e=oWfjTb) a z dalsich detailov, ktore nam este poskytnu zadavatelia katalog poziadaviek (https://liveuniba-my.sharepoint.com/:w:/g/personal/hrcka10_uniba_sk/EQawkAakEyRDvaT5IPfKTZUBkP5rgMc2-FOc7PTiIrCJyw?e=4oyQt7)

**Comment by nofiv** [comment]
inspiracia: https://github.com/TIS2019-FMFI/project-risk-analysis/blob/master/Dokumentacia.pdf
prehladnejsia inspiracia: https://github.com/TIS2019-FMFI/endurance-testing/blob/master/Dokumentacia.pdf
samostatny navrh a vsetko: https://github.com/TIS2019-FMFI/meranie-velicin/blob/master/Documentation/navrh.pdf

**Comment by nofiv** [comment]
uvod chce spravit @muriga

**Comment by nofiv** [comment]
vseobecny popis spravim ja

**Comment by nofiv** [comment]
zvysne poziadavky @petrilak3 a @13andrej

**Comment by muriga** [comment]
Mám trochu issue s týmto issue - mám práva iba na čítanie dokumentu, kde má byť Katalóg.
https://liveuniba-my.sharepoint.com/:w:/g/personal/hrcka10_uniba_sk/EQawkAakEyRDvaT5IPfKTZUBUyiZtA7R2baSgM65E9pYig?e=AidhTo

**Comment by nofiv** [comment]
> Mám trochu issue s týmto issue - mám práva iba na čítanie dokumentu, kde má byť Katalóg.
> https://liveuniba-my.sharepoint.com/:w:/g/personal/hrcka10_uniba_sk/EQawkAakEyRDvaT5IPfKTZUBUyiZtA7R2baSgM65E9pYig?e=AidhTo

Bol si prihlásený s tým uniba účtom? Fungovalo to včera keď sme to testovali

**Comment by nofiv** [comment]
> vseobecny popis spravim ja

vseobecny popis je uz podla mna vo finalnom stave, mozte pripomienkovat

**Comment by petrilak3** [comment]
https://github.com/TIS2020-FMFI/dalekohlad/wiki/Stretnutie-so-zadávateľmi-č.2

Poznámky zo stretnutia 23.10 o 10:00. Je potrebné všetky body zakomponovať do katalógu a poslať p.Petrovičovi na schválenie.
* najlepšie ešte dnes (23.10.2020 do 23:59)

**Comment by petrilak3** [comment]
Katalóg požiadaviek bol odoslaný na schválenie p.Petrovičovi : 23.10.2020 o 16:57

**Comment by pavelpetrovic** [comment]
Ďakujem za aktualizovaný KP.

Vyzerá to už celkom pekne, urobil som niekoľko drobných úprav (je zapnuté sledovanie úprav, takže to uvidíte) a pridal niekoľko zvýrazňovačom označených komentárov.

Z pôvodného stretnutia si pamätám, že zadávatelia mali záujem meniť niekoľko hodnôt naraz potvrdením celej skupiny zadaných hodnôt, čo im aktuálna textová verzia neumožňovala, ale zatiaľ nič také v tomto KP nevidím. Môžete sa aj k tomu vyjadriť, prosím?
[TIS_katalog_poziadaviek_s_komentarmi.docx](https://github.com/TIS2020-FMFI/dalekohlad/files/5443176/TIS_katalog_poziadaviek_s_komentarmi.docx)

**Comment by petrilak3** [comment]
@pavelpetrovic 

Každý člen teamu aktualizoval svoju časť KP na základe Vašich komentárov a pripomienok. Určité upravené body a náš postup sú vysvetlené v komentároch v katalógu.

Vaša otázka: 
Na stretnutí sme zadávateľom navrhli, že by existoval jeden mater button, ktorým by sa odoslali všetky zmenené/nastavené hodnoty. To bohužiaľ zamietli.
Ďalšia idea bola z ich strany, že by existovali určité skupiny (presne neurčené, ale približne: Polar a Declination axis, Camera, Filterwheel, Target, Dome), kde by existoval pre každú skupinu master button, ktorý by odoslal nastavené hodnoty z týchto skupín. 
Táto idea ale zatiaľ nebola schválená a bolo nám oznámené, že si to majú zadávatelia prekonzultovať medzi sebou, dohodnúť sa a dať nám vedieť, ale predpokladá sa verzia (čo je aj naša momentálna požiadavka), že sa budú hodnoty odosielať postupne (napr. kliknutím na button "Enable motors" sa odošle na backend zapnutie motorov, a podobne....).
Dali sme všeobecnú požiadavku ako OPTIONAL s týmto znením, ale kedže nevieme ani presné rozdelenie skupín a zatiaľ neprišla odpoveď, tak predpokladáme, že ostávame pri starej verzii.
* Osobný názor: hlavný dôvod je pravdepodobne to, že nemá zmysel odosielať skupiny príkazov. Odosielanie skupiny nejakých príkazov alebo ich postupné odosielanie nemá žiaden rozdielny vplyv.

**Comment by pavelpetrovic** [comment]
dakujem za vysvetlenie


> Osobný názor: hlavný dôvod je pravdepodobne to, že nemá zmysel odosielať skupiny príkazov. Odosielanie skupiny nejakých príkazov alebo ich postupné odosielanie nemá žiaden rozdielny vplyv.

s tymto by som si dovolil polemizovat :)
lebo je velky rozdiel, ci najskor stlacim jeden klaves a hned sa zacne
podla neho nieco diat a potom o par sekund (alebo desatin sekundy)
stlacim druhy klaves a zacne sa diat este nieco ine, ako ked
to odstartujem podla pripravenych hodnot naraz. ved prave o to ide.

idem si teda pozriet KP, ak ho najdem

**Comment by pavelpetrovic** [comment]
nenasiel som, mate ho niekde?

**Comment by pavelpetrovic** [comment]
uz som ho nasiel v mailoch :)

**Comment by pavelpetrovic** [comment]
Chválim Vás, dobrá práca!

Posledné drobnosti:

Opravte, prosim, este slovo "interpreter" v 2.5 napr. na "java runtime environment". 
(Java nie je interpretovana, ale kompilovana do bytecode a bezi na virtualnom stroji)

Ak by sa Vám ešte podarilo vymeniť termín "JSON súbor" za "JSON štruktúra", tak by to bolo potešujúce,
lebo to pokiaľ rozumiem nebude žiaden súbor v terminológií operačných systémov, ale len JSON štruktúra v pamäti.

Pošlite to teda v takejto podobe, prosím a požiadajte ich, aby to dôkladne skontrolovali, že podľa tohto
to naprogramujete, pripomente im teda otázku ako s tými skupinami hodnôt a že podľa toho upravíte 3.1.4.2.

Tiež by ste im mohli navrhnúť, že ak nemajú čas, tak ten JSON formát môžete aj sami navrhnúť, že do neho jednoducho za radom nasypete všetky položky, ktoré sú v KP vymenované.

**Comment by petrilak3** [comment]
KP bol upravený a odoslaný 28.10.2020 o 8:15 zadávateľom. Do e-mailu boli priložené aj otázky a bolo požiadané o dôkladné prečítanie katalógu.

**Comment by petrilak3** [comment]
UPDATE: dnes 29.10.2020 o 12:00 prišla odpoveď na katalóg požiadaviek : _ďakujeme Vám za dokumenty, v priebehu budúceho týždňa Vám ich pošleme späť s prípadnými poznámkami — takisto aj pre wireframe z predchádzajúceho mailu._

zároveň odpovede na otázky:

- Bod 3.4.1.2 ohľadom master buttonov na odosielanie skupiny príkazov: _Ešte sme Váš návrh nestihli prebrať s ostatnými pozorovateľmi._
- návrh, o môžnosti vytvorenia JSON struktúrý na našej strane. + Info o emulátore a JSON-e:  _Ako sme spomínali minulý týždeň na stretnutí, práca sa dá začať aj bez emulátora. Ten je potrebný až na testovanie samotných rozhraní._

**Comment by petrilak3** [comment]
UPDATE:
dnes (9.11.2020) poobede je sľúbený deadline od zadávateľov, kde majú poslať späť katalóg aj návrh + termín stretnutia.
Ako ste už videli v maily, vyzerá, že je to super a budú len maličké zmeny.

**Comment by petrilak3** [comment]
9.11.2020 večer nám bol doručený katalóg požiadaviek a aj návrh GUI, ktorý sme prediskutovali na teamovom stretnutí dňa 10.11.2020, kde sa nachádzajú aj všetky pripomienky.
V ďalšom pláne je zapracovať všetky zistenia a nedostatky.

Stretnutie so zadávateľmi je dohodnuté na piatok : 13.11.2020 o 10:00 cez MS Teams

**Comment by petrilak3** [comment]
Zadávateľom bola doručená posledná verzia katalógu požiadaviek, ku ktorej nemal žiadne ďalšie pripomienky.
To znamená, že dokument Katalóg požiadaviek je úspešne ukončený.
