### ISSUE TITLE
odovzdávanie prototypu

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2020-FMFI/dalekohlad#71]

**Comment by pavelpetrovic** [comment]
takto odpísali:

Date: Fri, 11 Dec 2020 12:59:09 +0000
From: Šilha Jiří <jiri.silha@fmph.uniba.sk>
To: Pavel Petrovic <petrovic@ii.fmph.uniba.sk>
Subject: Re: TIS projekt GUI ďalekohľad

Dobrý deň,

budúci týždeň budeme mať človeka na AGO, možno tam aj pôjdeme kvôli pozorovaniam, implemntáciám. Môžeme skúsiť rovno aj GUI od študentov.
+Ak nie, vieme s kolegom Krajčovičom to otestovať na emulatore.

Kľudne nám to teda môžete poslať.

Ďakujem.

S pozdravom,
Jiri Silha

Division of Astronomy and Astrophysics
Department of Astronomy, Physics of the Earth and Meteorology
Faculty of Mathematics, Physics and Informatics
Comenius University
Mlynska Dolina
842 48 Bratislava, Slovakia
Tel:  +421 2 602 95 630
Fax: +421 2 654 25 982

**Comment by pavelpetrovic** [comment]
skúste sa s nimi prípadne skoordinovať

**Comment by petrilak3** [comment]
@pavelpetrovic dnes bol odoslaný prototyp zadávateľom na otestovanie. :)

**Comment by petrilak3** [comment]
@pavelpetrovic @nofiv @13andrej @muriga 

Odpoveď:

Dobrý deň pán Petriľak,

program sa nám podarilo spustiť. Čo sa týka funcionalít zaimplementovaných do GUI, tie vyzerajú byť v poriadku, keď to porovnáme s katalógom požiadaviek TIS. 

Kolega Mrg. Krajčovič ešte spustí Váš program s emulátorom. Začiatkom januára Vám dáme vedieť naše stanovisko. Verím však, že ak ste použili kolegov emulátor a išlo Vám to pri Vašich testoch, nemusíme očakávať žiadne komplikácie a nemali by byť potrebné dodatočné implementácie. 

Pekné sviatky prajem.

S pozdravom,
Jiri Silha

Division of Astronomy and Astrophysics
Department of Astronomy, Physics of the Earth and Meteorology
Faculty of Mathematics, Physics and Informatics
Comenius University
Mlynska Dolina
842 48 Bratislava, Slovakia
Tel:  +421 2 602 95 630
Fax: +421 2 654 25 982

**Comment by petrilak3** [comment]
@pavelpetrovic

Mail od zadávateľov ohľadom stanoviska. Požiadal som ich, aby informovali aj Vás kvôli validácii.

**MAIL:**

Dobrý deň Petriľak,

aplikácia/GUI spĺňa všetky náležitosti, ktoré sme vyžadovali s Mgr. Krajčovičom. Ja som skontroloval splenie požiadaviek funcionalít, zatiaľ čo kolega Krajčovič skontroloval samotný kód. Preto vývoj GUI môžeme požadovať za uzavretý. 

Náš ďalší krok bude inštalácia (deployment) na kontrolnom počítači AGO70 (to už je mimo Váš predmet). Keby sme nemali pandémiu, prizvali by sme aj váš tím na observatórium, aby ste videli, ako GUI vyzerá v praxi. Samozrejme, akonáhle to budeme mať spojazdnené, zašleme Vám video ako sa GUI ďalekohľadu využíva.

Čo sa mňa a Mgr. Krajčoviča týka, splnili ste všetko, čo bolo pre nás v tomto predmete potrebné splniť.

Ďakujem za veľmi efektívnu spoluprácu a prajem všetko dobré.

S pozdravom,
Jiri Silha

Division of Astronomy and Astrophysics
Department of Astronomy, Physics of the Earth and Meteorology
Faculty of Mathematics, Physics and Informatics
Comenius University
Mlynska Dolina
842 48 Bratislava, Slovakia
Tel:  +421 2 602 95 630
Fax: +421 2 654 25 982

**Comment by petrilak3** [comment]
@pavelpetrovic technická dokumentácia a proces odovzdávania boli dokončené a odoslané aj zadávateľom.
