### ISSUE TITLE
Prepínanie buttonov aj keď poslanie dát zlyhá

### ISSUE THREAD

**Issue by muriga** [TIS2020-FMFI/dalekohlad#77]
Pri disable motors a start scheduling sa buttony pri odoslaní zmenia na enable motors a stop scheduling aj keď sa príkaz neodošle.

**Comment by muriga** [comment]
Ešte mi napadá, nemalo by čosi podobné robiť aj pri pole crossing on?

**Comment by petrilak3** [comment]
ano malo :)

**Comment by petrilak3** [comment]
vyriesenie  #79
