### ISSUE TITLE
cakanie na godota

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#8]
ked pridu zvysne detaily zadania, pridat ich do #7

**Comment by nofiv** [comment]
Ked pridu je potrebne aktualizovat sekciu 2.2. v katalogu poziadaviek (https://liveuniba-my.sharepoint.com/:w:/g/personal/hrcka10_uniba_sk/EQawkAakEyRDvaT5IPfKTZUBkP5rgMc2-FOc7PTiIrCJyw?e=4oyQt7). Konkretne je potrebne definovat co obnasaju "informácie o aktuálnom stave konfigurácie ďalekohľadu" a specifikovat tu "upozornenia pri nevhodne zvolenej konfiguracii dalekohladu"

**Comment by petrilak3** [comment]
Zvyšné detaily pre katalóg požiadaviek boli objasnené na stretnutí číslo 2 a sú úspešne pridané do katalógu požiadaviek.
