### ISSUE TITLE
javafx double buffering - v pripade blikania

### ISSUE THREAD

**Issue by nofiv** [TIS2020-FMFI/dalekohlad#9]
https://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferStrategy.html

**Comment by pavelpetrovic** [comment]
ta linka sa tyka asi viac AWT, pre JavaFX asi netreba robit double-buffering lebo ten nakresli cely obsah az ked sa mu povie, ak som to pochopil, nejake info napr. tu: 
https://stackoverflow.com/questions/36459710/javafx-canvas-double-buffering
